### PR TITLE
Improve Userstyle

### PR DESCRIPTION
**Pull request by Pegioner**

### CODE REVIEW

**Comment by cyfung1031** [comment]
Can you show me some screenshots "Before" and "After" for the changes you proposed? Thanks

**Comment by cyfung1031** [comment]
Thanks! I got it.

Few comments below:

1. I would like to have an option to enable/disable "very round corner" ( checkbox )
so the users can choose either before or after based on their preference.

2. I think it should be fine, but just could I ask you to install [YouTube Live Borderless](https://greasyfork.org/scripts/457317-youtube-live-borderless) to see whether there will be any weird things if we enable both userstyles. It's okay to just test the default settings with playing live video.

**Comment by Pegioner** [comment]
1. I've added the ability to select a custom rounding value ranging from 1px to 50px:
Снимок экрана 2023-10-10 в 21 51 35


2. As in your version, the rounding breaks when working with YouTube LiveBorderless. But I think it's not necessary when using YouTube LiveBorderless.

| Before | After |
|:-----:|:-----:|
| Снимок экрана 2023-10-10 в 22 10 29 | Снимок экрана 2023-10-10 в 22 04 39 |

**Comment by cyfung1031** [comment]
> P.S. Info is not displayed on the tab since 4.60.x

Can you tell me more? Can you open an issue if you think it is a bug?

**Pull request merged**
